### ISSUE TITLE
None of the charms are there

### ISSUE THREAD

**Issue by AliceLunaexe** [dpinela/Transcendence#13]
Hi, I was playing the mod and I looked in the locations but none of the charms are where they said to be. I have my mod list here. Idk if any of them could be conflicting with it. 

(If the pic isn't loading here are the mods:)
Modding API 1.5.78
Additional maps: 1.5
Benchwarp: 3.1.4.0
Benchwarp fix 
Cagneycarnation
CustomKinght
Debug
HK Discord RPC
Fennel
Hall of Gods Extras
Item changer
Menuchanger
More saves
QOL
Random pantheons
Randomizer4 (RandomizerCore)
Settings randomizer
Redo birthplace
Satchel
SFcore
Transcendence
Vasi

**Comment by dpinela** [comment]
Were you playing with the randomizer at the time?

**Comment by AliceLunaexe** [comment]
The randomizer was installed, but not active. I was using a current save
file

**Comment by dpinela** [comment]
You mean a save file that you'd already created before installing the mod? If so, that will not work - the charms are placed in the game at the time you create the save, so you'll need to make a new one to get them.

**Comment by AliceLunaexe** [comment]
Ah ok. Thank you. Thought my save file had finally bugged out on my end.
