### ISSUE TITLE
[Suggestions] Rando 4 logic

### ISSUE THREAD

**Issue by GamingInfinite** [dpinela/Transcendence#14]
Transcendence has the connection, but will sometimes lead to logic breaks like with the wings charm specifically.  Also please include the checks for the charms in the connection

**Comment by dpinela** [comment]
That the charms' abilities are not considered for logic is known. Updating logic to account for them will be very non-trivial, if and when it ever happens.

If by "include the checks for the charms in the connection", you mean adding the locations used for them in vanilla to the rando pool, I will not include that in this mod. It may happen as part of its own mod, which would probably add more locations besides the ones featured in Transcendence.
