### ISSUE TITLE
Randomize Notch Costs Adjustment

### ISSUE THREAD

**Issue by Drexl** [dpinela/Transcendence#16]
Does this mod do anything to take into account the randomized notch costs setting of rando4?

If not then by default all charms will become much cheaper on average as 35% more charms have been added to the game, but with the vanilla the total notch cost of +/- 20 (by default) set by the randomizer.

I couldn't find clear documentation on this.

**Comment by dpinela** [comment]
The notch costs of the Transcendence charms are randomized separately from the base game charms. Their costs do not deduct from the main notch total, but from a separate one set by Transcendence itself. You can see how that works here: https://github.com/dpinela/Transcendence/blob/05b167cabf46506ef577983811a8fb3c9c66d2da/Transcendence/Transcendence.cs#L427-L452

The minimum and maximum total costs for the Transcendence charms are hard-coded at 22 and 35 respectively. I've considered having some way of adjusting them but I haven't decided on one so far.
