### ISSUE TITLE
[Suggestion] Chaos Orb

### ISSUE THREAD

**Issue by MerRM** [dpinela/Transcendence#2]
Add an option that shows what charms Chaos Orb is currently imitating.
Something like RecentItemsDisplay mod would look good.

**Comment by dpinela** [comment]
I had that in mind. The main difficulty is that I would need to have all the sprites handy. (In the meantime, if you haven't noticed, you can see which charms it's imitating in your inventory)

**Comment by dpinela** [comment]
The latest major update has this - it's the "Chaos HUD" option in the menu.
