### ISSUE TITLE
Randomization fails with logic def error

### ISSUE THREAD

**Issue by SafetyFlux** [dpinela/Transcendence#26]
When attempting to use this with the Randomizer 4 mod, I run into an error that always prevents the game from generating, regardless of settings. It even prevents generation when the 'Add Charms' option is disabled.

The pastebin can be found [here](https://pastebin.com/tM6aBpPh). The error begins at line 166.

**Comment by dpinela** [comment]
Your Randomizer is out of date - you have 4.1.1+754, but the current version is 4.1.2+182. Updating it  should fix that error.

The apparent cause of the issue is that Transcendence is using the `Room_GG_Shortcut` waypoint, which exists in Rando 4.1.2 but not 4.1.1.

**Comment by SafetyFlux** [comment]
Wow, I didn't even notice that! It seems my Scarab launcher thought I had the latest version and wouldn't let me update. I was able to fix this by reinstalling Randomizer 4 and Core. Thank you!
