### ISSUE TITLE
Missing charms?

### ISSUE THREAD

**Issue by K1ngC001** [dpinela/Transcendence#28]
Throughout my playthrough I kept collecting charms and they would sometimes give me It and other times not. Most notably, Millibelle's Blessing and Marissa's Audience not showing up. Sometimes they would give the wrong icon or name too. Below is a picture of when I collected Marissa's Audience. 
![20240703193055_1](https://github.com/dpinela/Transcendence/assets/93218918/ff9bebd2-fead-4a8f-a8f1-b8fdd2ee4402)
It never showed up in my inventory and the charm isn't there on reload.
![Screenshot 2024-07-03 194623](https://github.com/dpinela/Transcendence/assets/93218918/43e7780c-c355-408c-92f4-3ea34a002680)
Is there a debug or something I could use to get it? Or is it a conflict with another mod.

**Comment by K1ngC001** [comment]
Now I tried getting the Bluemoth Wings and it gave me Snail Soul

**Comment by dpinela** [comment]
Did you perchance install or remove any mod that adds extra charms after you started that savefile?

**Comment by K1ngC001** [comment]
Not that I remember. Might've been Pale Court or Charm Crab.

**Comment by dpinela** [comment]
Charm Crab could very well be it - it's known to not interact well with other mods that significantly change gameplay; even [its README](https://github.com/DistractionCrab/Charm-Crab?tab=readme-ov-file#interactivity-with-other-mods) mentions that.

**Comment by K1ngC001** [comment]
Ahh I see, thanks for the help.
