### ISSUE TITLE
Feature Request: Make the mod togglable (at least for randomizer)

### ISSUE THREAD

**Issue by BadMagic100** [dpinela/Transcendence#3]
Transcendence should behave as other connections, i.e. it should be in the connections menu and be possible to be disabled without uninstalling. As is, it's cumbersome to toggle the mod on and off for different randomizers.

A functional alternative would be to make ITogglableMod, but this is probably actually harder to do

**Comment by dpinela** [comment]
It's not easy to do this (yet?) as SFCore (the mod that Transcendence uses to add the charms to the menu) doesn't let me remove charms after having added them. At most I could just not shuffle the items into the pool (for rando) / place them in the world (for vanilla) / give them to you (for Godseeker), but there would still be two permanently empty charm rows in your inventory.

**Comment by BadMagic100** [comment]
I think that's probably an ok approach. If I really needed it to be exactly like vanilla I'd uninstall it but I don't think having extra charm rows is an issue, as long as you can opt out in some way

**Comment by flibber-hk** [comment]
It might be worth making a feature request for SFCore?

**Comment by dpinela** [comment]
1.1 now has an option to not shuffle the charms into rando's pool. I think that's good enough; in vanilla/Godseeker you can always ignore the new charms entirely.
