### ISSUE TITLE
Charms not showing up

### ISSUE THREAD

**Issue by Ben-Jamin435** [dpinela/Transcendence#30]
When I open a save file from before I downloaded the mod, the charms do not show up when I try to find them. (Yes i'm looking in the correct spots) It works just fine for saves made after I got the mod though.

**Comment by dpinela** [comment]
This is the intended behaviour of the mod. Only saves created with Transcendence installed get the new charms; existing ones are not changed in any way.

**Comment by Ben-Jamin435** [comment]
oh ok
