### ISSUE TITLE
Feature Request: Give all of the charms in GodHome

### ISSUE THREAD

**Issue by osu4GBRAM** [dpinela/Transcendence#6]
I would like to use these in a GodHome exclusive save, so could you have these charms automatically given in GodHome saves?

**Comment by dpinela** [comment]
That is already implemented (in https://github.com/dpinela/Transcendence/commit/94535aff312d4cb5e67236675344e66b34645ac6) and will be in the next update. Stay tuned!

**Comment by dpinela** [comment]
Now available in version 1.1: https://github.com/dpinela/Transcendence/releases/tag/v1.1
