### ISSUE TITLE
[Suggestion] Millibelle's Blessing Balancing

### ISSUE THREAD

**Issue by Hotklou2404** [dpinela/Transcendence#7]
I've found that it is way too easy to gain huge amounts of Geo with this charm. So here are a few (mostly mutually-exclusive) ideas to change it to be a bit more balanced:
- Getting hit causes you to lose Geo, scaling with the amount of geo you have. Kind of like how Millibelle drops geo when you hit her after she stole your Geo and fled. I was thinking the amount of Geo you lose could be anything between 1x and 10x the interest rate (the amount of Geo you gain at each interval), which could perhaps be tweaked to the user's content in the mod's settings.
- Reduce the rate at which it scales with your geo slightly.
- Lengthen the interval at which you gain Geo from 5 seconds to something like 10 seconds.
- Do something to help prevent AFK-farming. I don't know what exactly can be done while still staying true to the theme of the charm. But perhaps it could have something to do with performing certain actions, such as killing an enemy, as you would not exactly be able to perform those actions while you are AFK.

**Comment by Hotklou2404** [comment]
There is actually a mod that makes you drop Geo from taking damage already. But you can't really tweak its values low enough for my tastes, at least not in the in-game mod menu - the lowest it can go is 20% of your geo each time you take damage. And it's on all the time (although there is an option to toggle it off), whereas I think something like it fits better as an additional effect for your "Millibelle's Blessing" charm.

**Comment by dpinela** [comment]
Thanks, but I don't intend to make any balance changes to the charms for the foreseeable future. I also don't plan on adding any configuration knobs (if nothing else because it's potentially a lot of configurations to debug and test and there's other things I'd like to do).
