### ISSUE TITLE
[Suggestion] Antigravity Amulet Name Change

### ISSUE THREAD

**Issue by Hotklou2404** [dpinela/Transcendence#8]
The word "antigravity" sounds a tad too sci-fi to me. I suggest switching it out for something like "slowfall", as many fantasy games have "Slowfall" potions or spells that make the player character fall slower, almost as if gravity does indeed have less of an affect on them. I rather like the sound of "Slowfall Amulet".

Or perhaps the entire theme of the charm could be changed and it could be called "Glidemaster"? As in, it gives the Knight the capability to glide through the air? The effect of the charm would stay the same though, this is just for aesthetics.

**Comment by dpinela** [comment]
I can understand the reasoning, but I'm happy with the charm names.
