### ISSUE TITLE
[Suggestion] Exaltation Mod Crossover

### ISSUE THREAD

**Issue by Hotklou2404** [dpinela/Transcendence#9]
This is probably wishful thinking, but I was thinking that it would be awesome if you could have a crossover with the Exaltation mod (https://github.com/TheodoreChristianRadu/Exaltation), allowing your charms to become "glorified" as well in Godhome by doing various Pantheons and challenges. Even if the charms didn't feature altered looks (right away), it would be great. What the exact changes for each charm would be after glorification, and the exact method for glorifying each charm is still up for debate.

**Comment by dpinela** [comment]
An interesting idea, although a) some of the Exhaltation charms overlap with the ones from Transcendence and b) the Transcendence charms are already powerful enough as it is.

**Comment by Hotklou2404** [comment]
I see that Primal Womb from Exaltation does indeed overlap with your Marissa's Audience... The rest could still be worked with though. I wasn't necessarily thinking something huge for *all* of them. I'll give you a list of ideas below (but keep in mind that they are only ideas and suggestions, not demands). :)

* Antigravity Amulet - Glorification reduces notch cost by 1. Perhaps it also boosts the effect of the charm slightly?

* Bluemoth Wings - Glorification reduces notch cost by 1. Geo per use decreased (by 5?).

* Florist's Blessing - I would actually recommend the base damage for this charm to be decreased slightly (to 2x maybe?) and/or its notch cost increased by 1, as those who are very skilled at the game, and don't take damage, can make way too good use of it. Its glorified version could see its damage bonus returned to its current value. Its new glorified name could be "Ze'mer's Blessing", implying that the Grey Mourner has regained at least some of her former fire for battle, and this has had some influence on the glorification of the charm, amplifying its power. For a new look for the charm it could be changed to have a more olden appearance, perhaps.

* Snail Slash - Glorigication decreases the damage penalty. Perhaps now it only decreases nail damage by 50% (or 75%)?

* Snail Soul - Glorification reduces notch cost by 1?

* Shaman Amp - I actually recommend changing its current name to something more Geo-themed, and re-using its current name on a new charm (more on that just below). Anyways, its glorification could see its notch cost decreased by 1.

Shaman Amp (new charm effect for a new charm by that name) - Increases spell damage when cast at full SOUL by something like 35%. Notch cost is 2. Encourages slow, thoughtful casting of spells. Glorification doubles its increases spell damage boost.

* Nitro Crystal - Glorification reduces notch cost by 1.
Another idea is that its current effect be changed to only increase Super Dash damage by 1.5x the base damage of your nail (meaning it starts low and increases as you upgrade your nail, and is unaffected by any other charms that increase nail damage). Whether the final amount should be rounded up or down is up for debate. Glorification could then (perhaps in addition to the -1 notch cost) increase this to 2x the base damage of your nail, ending up at a max of 42 damage when the player has a Pure Nail.

* Crystalmaster - Glorification reduces notch cost by 1. Other effects (being either as a replacement for the notch cost reduction or in addition to it) could include reducing the amount of geo consumed at each interval by a small amount, or increasing the interval (also resulting in a reduced rate of geo consumption).

* Disinfectant Flask - Glorification reduces notch cost by 1.

* Greedsong - Glorification \increases the upper limit of how much geo can be spawned and/or increases the lower limit (making it so that you are guaranteed an overall better result.

* Marissa's Audience - I can't think what can be done with it right now. Seeing as Exaltation has Primal Womb, Marissa's Audience's base effect might even have to be changed slightly. For now, it could just be left without a Glorified version.

* Chaos Orb - I actually recommend that its base notch cost should be increased by 1. I'm not sure what can be done with its glorification though. Maybe its charm cost could be reduced by 1, or its ability to give you charms could be improved (perhaps by increasing the number of charms it gives to 4, or increasing the time before reroll to 45 seconds?).

**Comment by Hotklou2404** [comment]
> An interesting idea, although a) some of the Exhaltation charms overlap with the ones from Transcendence and b) the Transcendence charms are already powerful enough as it is.

While I tried to not give too many ideas for changes to the base effects of your charms, I think more of them could use a look-over. You say they're already powerful enough as it is, but in my opinion a lot of them are a bit too powerful, at least for their notch cost. And making some of the more unbalanced ones a bit more balanced could also bring them down enough that there's space for improvement through glorification without making them even more unbalanced.

**Comment by Hotklou2404** [comment]
And as I see it, the whole glorification system is anyways meany to make charms a bit overpowered, both to create fun new things for the players to do and to help players who are struggling with the game (or more specifically the Pantheons) by giving them stronger charms to help overcome that gap. It's not always a problem of skill, sometimes (such as in my father's case), people are too physically ill to perform well enough, and Hollow Knight is not an easy game.

**Comment by dpinela** [comment]
Closing as it's very unlikely I'll ever want to do this.
